// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNtH1_bNldRJFsUhEbft_Ip18JDfLuvdY',
    appId: '1:453357502609:web:358e6fc3b0feb8c55d7f30',
    messagingSenderId: '453357502609',
    projectId: 'trial-5d05a',
    authDomain: 'trial-5d05a.firebaseapp.com',
    storageBucket: 'trial-5d05a.appspot.com',
    measurementId: 'G-84CHWDL48L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd9Krok_FNJuhHeu0U6jVcpp7yQMupx9M',
    appId: '1:453357502609:android:873b069c52a5d7325d7f30',
    messagingSenderId: '453357502609',
    projectId: 'trial-5d05a',
    storageBucket: 'trial-5d05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB18al_WyXNJ2leR-EDI4FRV1yGd2Xwyms',
    appId: '1:453357502609:ios:6585d90f73bc969c5d7f30',
    messagingSenderId: '453357502609',
    projectId: 'trial-5d05a',
    storageBucket: 'trial-5d05a.appspot.com',
    iosBundleId: 'com.example.envisionEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB18al_WyXNJ2leR-EDI4FRV1yGd2Xwyms',
    appId: '1:453357502609:ios:f853119bb83caf695d7f30',
    messagingSenderId: '453357502609',
    projectId: 'trial-5d05a',
    storageBucket: 'trial-5d05a.appspot.com',
    iosBundleId: 'com.example.envisionEye.RunnerTests',
  );
}
